compatibility_flags = ["streams_enable_constructors"]
compatibility_date = "2022-03-24"

[[ d1_databases ]]
binding = "DB"
database_name = "airish-tunes"
database_id = "88d892f9-027d-4495-b256-8a40fdeef118"
preview_database_id = "ec579f84-326f-443a-b66a-8ca8b9e75d71"

[[ r2_buckets ]]
binding = "R2"
bucket_name = "airish-tunes"
preview_bucket_name = "airish-tunes-dev"