CREATE TABLE tune_images (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date DATE NOT NULL,
	tune_name TEXT NOT NULL,
	the_session_tune_id TEXT NOT NULL,
	r2_key TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);